services:
  - type: web
    name: fortnite-scraper
    env: node
    buildCommand: npm install
    startCommand: node scrapeFortniteStats.js
    plan: free
    buildFilter:
      paths:
        - package.json
        - scrapeFortniteStats.js
        - render.yaml
    autoDeploy: true

    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"

    preBuildCommand: |
      apt-get update
      apt-get install -y \
        chromium-browser \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        xdg-utils \
        --no-install-recommends
